site_name: DicasDeEstagio - G5
#site_author: Mateus Villela
site_description: Site voltado para a documentação do Grupo 5 de Arquitetura e Desenvolvimento de Software - 2025.2
repo_url: https://github.com/UnBArqDsw2025-2-Turma02/2025.2-T02_G5_DicasDeEstagio_Entrega02
repo_name: 2025.2-DicasDeEstagio-Entrega1

theme:
  name: material
  logo: 'assets/imgs/LogoPrincipalG5.png'
  favicon: 'assets/imgs/LogoPrincipalG5.png'

  palette:
    - scheme: default
      primary: "#00543C"   # Verde Pantone 348
      accent: "#193A6A"    # Azul Pantone 654
      auxiliary: "#FFD600" # Amarelo Pantone 012C (contraste)
      toggle:
        icon: material/weather-night
        name: Modo escuro

    - scheme: slate
      primary: "#00543C"   # Verde Pantone 348
      accent: "#193A6A"    # Azul Pantone 654
      auxiliary: "#FFD600" # Amarelo Pantone 012C (contraste)
      toggle:
        icon: material/weather-sunny
        name: Modo claro

nav:
  - Início: index.md
  - 2. Desenho de Software (Modelagem):
    - 2.1. Introdução: Modelagem/index_modelagem.md
    - 2.2. UML Estático: 
      - 2.2.1. Visão Geral: Modelagem/estatica_uml/modelagem_estatica.md
      - 2.2.2. Diagrama de Classes: Modelagem/estatica_uml/diagrama_classes.md
    - 2.3. UML Dinâmico: 
      - 2.3.1. Visão Geral: Modelagem/dinamica_uml/modelagem_dinamica.md
      - 2.3.2. Diagrama de Estados: Modelagem/dinamica_uml/diagrama_estados.md
    - 2.4. UML Organizacional:
      - 2.4.1. Visão Geral: Modelagem/organizacional_uml/modelagem_organizacional.md
      - 2.4.2. Diagrama de Casos de Uso: Modelagem/organizacional_uml/diagrama_casos_uso.md
    - 2.5. Iniciativas Extras:
      - 2.5.1. Introdução: iniciativas_extras/index_iniciativas.md

markdown_extensions:
  - pymdownx.details
  - tables
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.arithmatex:
      generic: true

plugins:
  - search
  - mkdocs-pdf

extra_css:
  - assets/css/custom.css

extra_javascript:
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js