site_name: DicasDeEstagio - G5
#site_author: Mateus Villela
site_description: Site voltado para a documentação do Grupo 5 de Arquitetura e Desenvolvimento de Software - 2025.2
repo_url: https://github.com/UnBArqDsw2025-2-Turma02/2025.2-T02_G5_DicasDeEstagio_Entrega01
repo_name: 2025.2-DicasDeEstagio-Entrega1

theme:
  name: material
  logo: 'assets/imgs/LogoPrincipalG5.png'
  favicon: 'assets/imgs/LogoPrincipalG5.png'

  palette:
    - scheme: default
      primary: "#00543C"   # Verde Pantone 348
      accent: "#193A6A"    # Azul Pantone 654
      auxiliary: "#FFD600" # Amarelo Pantone 012C (contraste)
      toggle:
        icon: material/weather-night
        name: Modo escuro

    - scheme: slate
      primary: "#00543C"   # Verde Pantone 348
      accent: "#193A6A"    # Azul Pantone 654
      auxiliary: "#FFD600" # Amarelo Pantone 012C (contraste)
      toggle:
        icon: material/weather-sunny
        name: Modo claro

nav:
  - Início: index.md
  - Modelagem:
    - Introdução: modelagem/index_modelagem.md
    - UML Estático: 
      - Visao Geral: modelagem/estatica_uml/modelagem_estatica.md
    - UML Dinâmico: 
      - Visao Geral: modelagem/dinamica_uml/modelagem_dinamica.md
    - UML Organizacional:
      - Visao Geral: modelagem/organizacional_uml/modelagem_organizacional.md
  - Iniciativas Extras:
    - Introdução: iniciativas_extras/index_iniciativas.md

markdown_extensions:
  - pymdownx.details
  - tables
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.arithmatex:
      generic: true

plugins:
  - search
  - mkdocs-pdf

extra_css:
  - assets/css/custom.css

extra_javascript:
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js